name: khoneamee
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_switch: ^0.3.2
  get: ^4.6.5
  carousel_slider: ^4.1.1
  get_storage:
  socket_io_client: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/bg.jpg
    - assets/
